modLoader="javafml"
loaderVersion="${loader_version_range}"
# Only reenable if you have a issue tracker URL
issueTrackerURL="${mod_issues}"
license="${mod_license}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_url}"
logoFile="${mod_logo}"
credits="${mod_credits}"
authors="${mod_author}"
description='''${mod_description}'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="azurelib"
    type="required"
    versionRange="[${azurelib_version},)"
    ordering="BEFORE"
    side="BOTH"
[[mixins]]
    config = "${mod_id}.neoforge.mixins.json"
